name: Build Wheels (CUDA)

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build Wheel ${{ matrix.runtime.os }} ${{ matrix.cuda.version }}
    runs-on: ${{ matrix.runtime.os }}
    container: ${{ case(startsWith(matrix.runtime.os, 'ubuntu'), format('nvidia/cuda:{0}-devel-rockylinux9', matrix.cuda.version), null) }}
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - os: ubuntu-latest
            repair-command: "uvx --with patchelf auditwheel repair -w wheelhouse/ dist/*.whl"
          - os: ubuntu-24.04-arm
            repair-command: "uvx --with patchelf auditwheel repair -w wheelhouse/ dist/*.whl"
          - os: windows-latest
            repair-command: "uvx delvewheel repair --analyze-existing --ignore-existing -w wheelhouse/ dist/*.whl"
        cuda:
          - version: "12.6.3"
            tag: "126"
          - version: "12.8.1"
            tag: "128"
          - version: "13.0.2"
            tag: "130"

    permissions:
      contents: write

    steps:
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          dnf group install -y "Development Tools"
          dnf install -y openssl-devel

      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - uses: astral-sh/setup-uv@v8.0.0

      - name: Setup CUDA (Windows)
        uses: Jimver/cuda-toolkit@v0.2.35
        if: runner.os == 'Windows'
        with:
          cuda: ${{ matrix.cuda.version }}
          use-local-cache: false
          use-github-cache: false
          log-file-suffix: ${{ matrix.cuda.version }}

      - name: Extend $LD_LIBRARY_PATH (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/compat" >> $GITHUB_ENV

      - name: Extend PATH (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo $env:PATH
          "$env:CUDA_PATH/bin/x64" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      - name: Build wheel
        env:
          CMAKE_ARGS: "-DGGML_CUDA=ON -DGGML_CUDA_NO_VMM=ON -DGGML_CUDA_FORCE_MMQ=ON -DGGML_NATIVE=OFF"
          CMAKE_BUILD_PARALLEL_LEVEL: "8"
        run: uv build --wheel

      - name: Repair wheel
        run: |
          ${{ matrix.runtime.repair-command }}
          ls wheelhouse/

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.runtime.os }}-cu${{ matrix.cuda.tag }}
          path: wheelhouse/

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wheelhouse/*
          tag_name: ${{ github.ref_name }}-cu${{ matrix.cuda.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
